# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReadSDB
                                 A QGIS plugin
 Read data from PySDB database data into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-29
        copyright            : (C) 2021 by Ondrej Lexa
        email                : lexa@natur.cuni.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ReadSDB class from file ReadSDB.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .readsdb import ReadSDB
    return ReadSDB(iface)
