# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReadSDBDialog
                                 A QGIS plugin
 Read PySDB structural data into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-03
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Ondrej Lexa
        email                : lexa.ondrej@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from PyQt5 import uic
from PyQt5 import QtWidgets
from PyQt5.QtCore import Qt
from qgis.core import *

# Make sure that we are using QT5
import matplotlib
matplotlib.use('Qt5Agg')

# Need latest APSG
from apsg import StereoNet, folset, linset, fol, lin, apsg_conf
apsg_conf['dpi'] = 75

import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ui/readsdb_plot.ui'))


class MyMplCanvas(FigureCanvas):
    """Ultimately, this is a QWidget (as well as a FigureCanvasAgg, etc.)."""

    def __init__(self, parent=None):
        self.net = StereoNet()
        self.net.init_figure()
        super(MyMplCanvas, self).__init__(self.net.fig)
        #FigureCanvas.__init__(self, self.net.fig)
        self.setParent(parent)
        super(MyMplCanvas, self).setSizePolicy(
                                   QtWidgets.QSizePolicy.Expanding,
                                   QtWidgets.QSizePolicy.Expanding)
        super(MyMplCanvas, self).updateGeometry()


class ReadSDBPlotDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, readsdb, parent=None):
        """Constructor."""
        super(ReadSDBPlotDialog, self).__init__(parent, Qt.WindowStaysOnTopHint)
        self.setupUi(self)
        self.pushApply.clicked.connect(self.plotnet)
        self.data_layers = []
        self.canvas = MyMplCanvas(self)
        self.toolbar = NavigationToolbar(self.canvas, self)
        self.mplLayout.addWidget(self.canvas)
        self.mplLayout.addWidget(self.toolbar)
        self.net = self.canvas.net

    def opt(self, index, type, name):
        return self.tabWidget.widget(index).findChild(type, name)

    def plotnet(self):
        #self.net.grid = self.checkGrid.isChecked()
        self.net._kwargs["overlay"] = self.checkGrid.isChecked()
        self.net.clear()
        for idx, layer in self.data_layers[::-1]:  # plot in right order
            if layer.selectedFeatureCount():
                features = layer.getSelectedFeatures()
            else:
                features = layer.getFeatures()
            # Create data Group
            if layer._is_planar:
                g = folset([fol(f.attribute('azi'), f.attribute('inc')) for f in features], layer.name())
            else:
                g = linset([lin(f.attribute('azi'), f.attribute('inc')) for f in features], layer.name())
            label = repr(g) if self.checkLabels.isChecked() else ''
            # contours
            if self.opt(idx, QtWidgets.QCheckBox, 'checkContours').isChecked():
                nlevels = self.opt(idx, QtWidgets.QSpinBox, 'spinLevels').value()
                sigma = self.opt(idx, QtWidgets.QDoubleSpinBox, 'spinSigma').value()
                self.net.contour(g,
                                 levels=nlevels,
                                 sigma=sigma,
                                 colorbar=self.checkLabels.isChecked(),
                                 clines=self.opt(idx, QtWidgets.QCheckBox, 'checkContourLines').isChecked()
                                 )
            # plot data
            markersize = self.opt(idx, QtWidgets.QSpinBox, 'spinSize').value()
            marker = self.opt(idx, QtWidgets.QComboBox, 'comboStyle').currentText()
            if layer._is_planar:
                if self.opt(idx, QtWidgets.QCheckBox, 'checkShowData').isChecked():
                    if self.opt(idx, QtWidgets.QCheckBox, 'checkAsPoles').isChecked():
                        self.net.pole(g, marker=marker, ms=markersize, label=label)
                    else:
                        self.net.great_circle(g, label=label)
            else:
                if self.opt(idx, QtWidgets.QCheckBox, 'checkShowData').isChecked():
                    self.net.line(g, marker=marker, ms=markersize, label=label)
            ## principal
            if self.opt(idx, QtWidgets.QCheckBox, 'checkEigPlanes').isChecked():
                self.net.great_circle(*g.ortensor().eigenfols, label='E-fols' if self.checkLabels.isChecked() else '')
            if self.opt(idx, QtWidgets.QCheckBox, 'checkEigLines').isChecked():
                self.net.line(*g.ortensor().eigenlins, marker='s', ms=8, label='E-lins' if self.checkLabels.isChecked() else '')

        self.net.render()
        self.canvas.draw()
